
import React, { useEffect } from 'react';
import { ArrowLeft, FileText } from 'lucide-react';

interface PageProps {
  onBack: () => void;
}

const TermsPage: React.FC<PageProps> = ({ onBack }) => {
  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);

  return (
    <div className="min-h-screen w-full bg-[#FDF2F8] font-sans text-[#5e3a58]">
      {/* Header */}
      <div className="sticky top-0 z-10 bg-[#FDF2F8]/90 backdrop-blur-md border-b border-[#B28DFF]/20 px-6 py-4 flex items-center gap-4">
        <button 
          onClick={onBack}
          className="p-2 -ml-2 rounded-full hover:bg-black/5 text-[#5e3a58] transition-colors"
        >
          <ArrowLeft size={24} />
        </button>
        <h1 className="text-xl font-serif-display font-bold text-[#4A2040]">Terms of Service</h1>
      </div>

      {/* Content */}
      <div className="max-w-2xl mx-auto px-6 py-8 space-y-8">
        
        <p className="leading-relaxed opacity-90 text-sm">
          Welcome to CallHub AI. Please read these terms carefully before using our platform. By accessing or using this service, you agree to the rules outlined below.
        </p>

        <section className="space-y-3">
          <h3 className="text-lg font-bold text-[#4A2040]">1. Eligibility</h3>
          <p className="opacity-90">
            You must be at least 18 years old to access or use CallHub AI. By using this website, you confirm that you meet this age requirement.
          </p>
        </section>

        <section className="space-y-3">
          <h3 className="text-lg font-bold text-[#4A2040]">2. Nature of the Service</h3>
          <p className="opacity-90">CallHub AI is an entertainment platform providing AI-generated text and voice interactions.</p>
          <ul className="space-y-2 list-disc pl-5 opacity-90">
            <li>The characters you interact with are <strong>fictional</strong> and generated by artificial intelligence.</li>
            <li>This is <strong>not</strong> a dating service for meeting real human beings.</li>
            <li>The AI may occasionally generate incorrect or unpredictable responses.</li>
          </ul>
        </section>

        <section className="space-y-3">
          <h3 className="text-lg font-bold text-[#4A2040]">3. Prohibited Behavior</h3>
          <p className="opacity-90">To keep this platform safe for everyone, you agree <strong>not</strong> to:</p>
          <ul className="space-y-2 list-disc pl-5 opacity-90">
            <li>Use the service for any illegal purpose.</li>
            <li>Harass, abuse, or use hate speech within the platform.</li>
            <li>Attempt to hack, reverse-engineer, or exploit the website’s code or infrastructure.</li>
            <li>Upload content that depicts non-consensual sexual acts, violence, or minors.</li>
            <li>Impersonate others or misrepresent your identity.</li>
          </ul>
        </section>

        <section className="space-y-3">
          <h3 className="text-lg font-bold text-[#4A2040]">4. Content Ownership</h3>
          <ul className="space-y-2 list-disc pl-5 opacity-90">
            <li><strong>Your Content:</strong> You retain rights to any photos or specific text inputs you upload to the platform.</li>
            <li><strong>Platform Content:</strong> CallHub AI retains rights to the AI technology, the generated character behaviors, and the interface design.</li>
            <li><strong>No Resale:</strong> You may not use the AI-generated responses or voice audio for commercial resale or redistribution.</li>
          </ul>
        </section>

        <section className="space-y-3">
          <h3 className="text-lg font-bold text-[#4A2040]">5. AI Disclaimer</h3>
          <p className="opacity-90">
            The AI companions on this platform are for entertainment and emotional comfort only. They are not professionals. The AI cannot and should not be used as a substitute for professional advice, including legal, medical, or psychological help.
          </p>
        </section>

        <section className="space-y-3">
          <h3 className="text-lg font-bold text-[#4A2040]">6. Payments & Subscriptions</h3>
          <p className="opacity-90">
            If you choose to purchase any premium features or subscriptions, these transactions are handled via third-party payment providers (e.g., Google Play, Stripe). All subscriptions are subject to the terms and refund policies of those specific providers.
          </p>
        </section>

        <section className="space-y-3">
          <h3 className="text-lg font-bold text-[#4A2040]">7. Account Termination</h3>
          <p className="opacity-90">
            We reserve the right to suspend or terminate access to the platform for any user who violates these Terms of Service. Users may also request to delete their own accounts at any time.
          </p>
        </section>

        <section className="space-y-3">
          <h3 className="text-lg font-bold text-[#4A2040]">8. Limitation of Liability</h3>
          <p className="opacity-90">
            CallHub AI is provided on an "as-is" and "as-available" basis. While we strive for a smooth experience, we are not liable for service downtime, data loss, or emotional outcomes resulting from interactions with the AI.
          </p>
        </section>

        <section className="space-y-3 bg-white/50 p-6 rounded-2xl border border-white/60">
          <h3 className="text-lg font-bold text-[#4A2040]">Contact Us</h3>
          <p className="opacity-90 mb-2">For legal inquiries or questions regarding these terms, please contact:</p>
          <a href="mailto:legal@callhub.in" className="text-[#B28DFF] font-medium hover:underline block">
            legal@callhub.in
          </a>
        </section>

      </div>

      {/* Footer */}
      <footer className="py-8 px-6 text-center border-t border-[#B28DFF]/10 bg-[#FFF0F5]">
        <p className="text-[#5e3a58]/60 text-xs font-medium leading-loose">
          © 2025 CallHub • All Rights Reserved • 18+ Only<br/>
          Designed for safe, private emotional AI interactions
        </p>
      </footer>
    </div>
  );
};

export default TermsPage;